### PR TITLE
initial setup

### PR DESCRIPTION
**Pull request by alope107**
Created initial template for our project!  Note that unlike our hello-world the .gitignore is NOT inverted. Also, please remember to fork your own copy of the repository before you begin work. Please attempt to manually test this build using the included QR code. If sharing QR codes works, then we should include them on any PR that involves a UI change, so that the reviewers can inspect what was changed.

screen shot 2015-11-06 at 5 10 01 pm

### CODE REVIEW

**Comment by athattayathu** [comment]
After a bit of research, when it comes to the plugins directory, people recommend ignoring the contents of the plugins folder from version control. There will be an error on the build if the plugin folder is not present so we should commit an empty plugin folder.

**Comment by alope107** [comment]
That makes sense. Is there some file where we specify plugins so that cordova can automatically download them? It would be cumbersome to force everyone to manually a new plugin each time we add one.

**Comment by alope107** [comment]
Found the solution to my question. When adding a plugin, use `cordova plugin add PLUGINNAME --save --shrinkwrap`
This adds the plugin info to config.xml

**Comment by athattayathu** [comment]
[This site](http://devgirl.org/2013/11/12/three-hooks-your-cordovaphonegap-project-needs/), although 2 years old, proposes the plugin download job be a hook.

The latest suggestion would be to utilize the save and prepare feature added in the [April 15th update of Cordova](https://cordova.apache.org/news/2015/04/21/tools-release.html). [Here](http://www.raymondcamden.com/2015/04/21/big-updates-to-apache-cordova) is a rundown of the usage of the feature

**Pull request merged**
